### PR TITLE
Mastodon support

### PR DESCRIPTION
**Pull request by andrlik**
Allows users to set up Mastodon accounts as a source of corpus data and also use Mastodon as a an additional or alternative target for the resulting Markov sentence. Relates to issue #42

### CODE REVIEW

**Comment by tommeagher** [comment]
Wow, @andrlik, this is amazing. I hadn't even considered Mastodon yet. Thanks for this PR. I'll review this in the next week or so before I merge. I'll holler if I have any questions. Do you have this running live on a Mastodon account now?

**Comment by andrlik** [comment]
Yep, it’s what is posting to [@andrlik_ebooks@botsin.space](https://botsin.space/@andrlik_ebooks). It pulls both the tweets from my Twitter account, and any of the Mastodon toots from my primary Mastodon account. There is one limitation in that statuses on Mastodon don’t federate to other instances unless someone on that foreign instance follows the account (in which case the statuses appear in both places for anyone), so the bot can only pull whatever history exists on its instance. The only way around that would be create the bot on the same instance, but that would depend on the rules about bots on that instance.

**Comment by andrlik** [comment]
Hi, any updates on this PR? Thanks!

**Comment by tommeagher** [comment]
Hi @andrlik, I haven't forgotten about this. I'm still very excited and glad to have it. Just need to carve out a little time to give it some attention. I fully intend to and will let you know when I inevitably have questions. Thank you!

**Comment by andrlik** [comment]
I have now made it so that you can choose your posting targets independently of the enabled sources.

**Comment by tommeagher** [comment]
Awesome, @andrlik. Thanks for adding that. This is great. Happy to merge this into master. Thank you!

**Pull request merged**
