### PR TITLE
Remove local_settings.py from .gitignore

### LINKED ISSUE #54: ModuleNotFoundError: No module named 'local_settings'
I have set up this bot successfully once, in February this year using Twitter but I am now running into problems using it for Mastodon, but I don't think the problem is with either service.

I have followed all the steps described multiple times but I keep getting the following error when trying the first `heroku run worker` command:

```
Running worker on gentle-ridge-53367... up, run.1762 (Free)
Traceback (most recent call last):
  File "ebooks.py", line 17, in <module>
    from local_settings import *
ModuleNotFoundError: No module named 'local_settings'
```

I've definitely got the correct file name etc and I've tried changing the runtime.txt several different versions of Python to see if it makes any difference but it doesn't? Have attached my local_settings.py file in case there's something obvious that I've somehow missed. For the record I am very new to coding so I apologise if I'm just wasting your time with a mistake I've made.

[local_settings (copy).txt](https://github.com/tommeagher/heroku_ebooks/files/2343131/local_settings.copy.txt)

### PR DESCRIPTION
**Pull request by TimLChan**
Will fix #54 and all issues that are similar in the future

### CODE REVIEW

**Comment by tommeagher** [comment]
Hmmm. I think the idea of putting local_settings.py into .gitignore was to prevent people from accidentally posting it on Github. But that also makes it trickier for users to get it to Heroku if they have to remember to add it without seeing it in ```git status```. Is there any other way to mitigate this, or should we just put a note in the README to be careful not to post your creds on Github?

**Comment by TimLChan** [comment]
It depends on the workflow of the user and how strict they want to protect their data.

Local -> Heroku: It won't touch GitHub so there's no need to hide `local_settings.py`
Local -> Github -> Heroku: `local_settings.py` will be on GitHub, so it should be added to `.gitignore`

For Local -> GitHub -> Heroku, [Environment Variables](https://devcenter.heroku.com/articles/config-vars) can be used, and you can refer to them in the config as something like the below
```
MY_CONSUMER_KEY = os.environ['consumerkey'] #'Your Twitter API Consumer Key'
MY_CONSUMER_SECRET = os.environ['consumersecret'] #'Your Consumer Secret Key'
MY_ACCESS_TOKEN_KEY = os.environ['accesskey'] #'Your Twitter API Access Token Key'
MY_ACCESS_TOKEN_SECRET = os.environ['accesssecret'] #'Your Access Token Secret'
```

**Comment by tommeagher** [comment]
I think we should move toward using the environment variables in Heroku config. That’s a best practice I’ve adopted in all my projects in recent years. We can also remove .csv from .gitignore. 
Are you willing to take a stab at this in the local_settings.py and the README? If not, I can do it.

**Comment by tommeagher** [comment]
Hey @TimLChan, I cut a new release today that moves those API keys to Heroku environment variables, per your suggestion. Take a look and see if anything is amiss: https://github.com/tommeagher/heroku_ebooks/releases/tag/v0.3.0

**Pull request merged**
