### PR TITLE
Added Python3 compatibility

### PR DESCRIPTION
**Pull request by ekevoo**
I know that `runtime.txt` explicitly asks for 2.7.13, but I happen to not have 2.7 locally and adding Python 3 support was easy and unobtrusive enough. Well, at least I thought it was. ;)

### CODE REVIEW

**Comment by tommeagher** [comment]
Ooooh. This is awesome. Thank you so much for contributing this. I'll review and test and merge this soonish. Thanks again!

**Comment by ekevoo** [comment]
Do you have any questions for clarification?

**Comment by tommeagher** [comment]
Nope. No questions. It looks super straight forward. I just haven't had a
chance to run it for myself to test. Will do so pronto. Thank you so much
for contributing and for the reminder.

**Comment by tommeagher** [comment]
This looks great and seems to work fine. @ekevoo, should we update the runtime.txt or remove it?
Is it also worth mentioning in the README that it now supports Python3, too?

**Comment by ekevoo** [comment]
I agree with updating the readme-- that didn't occur to me at all.

I would've coded a bit differently if the plan was upgrading the runtime to
Python 3. I did it pretty py-2 centric. But that's just semantics, it works
nonetheless, so it's a fine idea, too.

**Comment by tommeagher** [comment]
@ekevoo do you want to take a crack at making those tweaks?

**Comment by ekevoo** [comment]
Yeah sure! I'll do that in the weekend :)

**Comment by ekevoo** [comment]
I couldn't find anything in the README on which version of Python it uses, so I didn't touch that.

**Comment by tommeagher** [comment]
Merged this. Thank you, @ekevoo!

**Pull request merged**
