### PR TITLE
Add rudimentary web scraping

### PR DESCRIPTION
**Pull request by ConorIA**
Added rudimentary web scraping, as implemented in: https://twitter.com/academic_ebooks, which pulls vocab from http://www.pnas.org/reports/most-cited.

### CODE REVIEW

**Comment by tommeagher** [comment]
Awesome. Thank you! I'll take a look and try to merge this soon.

**Comment by ConorIA** [comment]
@tommeagher, thanks. I think there are ways to improve this. Such as using multiple pages and a more flexible way to extract info using beautiful soup. I'll probably take another crack at this in the coming days, so maybe hold off on the merge for the time being.

**Comment by tommeagher** [comment]
@ConorIA cool, let me know when you're done and I'll take a look.

**Comment by ConorIA** [comment]
@tommeagher, I think that it is now as good as it is going to get. I bet there is much more that could be done, but I have exhausted my limited knowledge. 

The last commit I made was a little presumptuous. Essentially it allows one to scrape website _and_ use Twitter as a source as well. If you would rather have these sources siloed, let me know, and I will revert.

**Comment by tommeagher** [comment]
Superseded by #41

**Pull request closed without merging**
